//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpNetCoreDesafioB2.Queries.General {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpNetCoreDesafioB2.Queries.General.GeneralQueries", typeof(GeneralQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BEGIN;
        ///TRUNCATE TABLE mantis_filters_table; 
        ///TRUNCATE TABLE mantis_bug_text_table;
        ///TRUNCATE TABLE mantis_bug_table;
        ///TRUNCATE TABLE mantis_tag_table;
        ///TRUNCATE TABLE mantis_bug_tag_table;
        ///TRUNCATE TABLE mantis_custom_field_table;
        ///TRUNCATE TABLE mantis_user_profile_table;
        ///TRUNCATE TABLE mantis_project_table;
        ///TRUNCATE TABLE mantis_category_table;
        ///#DELETE FROM mantis_category_table WHERE id !=1;
        ///COMMIT;.
        /// </summary>
        internal static string ClearBD {
            get {
                return ResourceManager.GetString("ClearBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BEGIN;
        ///#Criar um  projeto em base
        ///INSERT into mantis_project_table (NAME,description,inherit_global) values (&apos;Proj Trigger&apos; , &apos;Descrition Trigger&apos;, 1) ;
        ///#Criar uma tarefa base
        ///INSERT INTO mantis_bug_table 
        ///(project_id,reporter_id,handler_id,duplicate_id,priority,severity,reproducibility,STATUS,resolution,projection,
        ///eta,bug_text_id,os,os_build,platform,version,fixed_in_version,build,profile_id,view_state,summary,sponsorship_total,sticky,target_version,
        ///category_id)
        ///VALUES(1,1,0,0,30,50,70,10,10,10,1 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string GlobalMass {
            get {
                return ResourceManager.GetString("GlobalMass", resourceCulture);
            }
        }
    }
}
