//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpNetCoreDesafioB2.Queries.Projects {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectsQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectsQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpNetCoreDesafioB2.Queries.Projects.ProjectsQueries", typeof(ProjectsQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRUNCATE TABLE mantis_project_hierarchy_table.
        /// </summary>
        internal static string ClearHierarchyProject {
            get {
                return ResourceManager.GetString("ClearHierarchyProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT COUNT(*) AS projetos FROM mantis_project_table;.
        /// </summary>
        internal static string CountProjectBD {
            get {
                return ResourceManager.GetString("CountProjectBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ID,NAME FROM mantis_project_table
        ///ORDER BY ID DESC
        ///LIMIT 1;.
        /// </summary>
        internal static string SearchIdAndProject {
            get {
                return ResourceManager.GetString("SearchIdAndProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ID
        ///FROM mantis_project_table;.
        /// </summary>
        internal static string SearchIdProjects {
            get {
                return ResourceManager.GetString("SearchIdProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ID FROM mantis_project_table
        ///ORDER BY RAND()
        ///LIMIT 1;.
        /// </summary>
        internal static string SearchIdProjectsRandom {
            get {
                return ResourceManager.GetString("SearchIdProjectsRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT parent_id FROM mantis_project_hierarchy_table
        ///ORDER BY RAND()
        ///LIMIT 1.
        /// </summary>
        internal static string SearchIdSubProjectsRandom {
            get {
                return ResourceManager.GetString("SearchIdSubProjectsRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT name FROM mantis_project_table
        ///ORDER BY RAND()
        ///LIMIT 1;.
        /// </summary>
        internal static string SearchNameProjectsRandom {
            get {
                return ResourceManager.GetString("SearchNameProjectsRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT NAME FROM mantis_project_table
        ///ORDER BY ID DESC
        ///LIMIT 1;.
        /// </summary>
        internal static string SearchProjectByName {
            get {
                return ResourceManager.GetString("SearchProjectByName", resourceCulture);
            }
        }
    }
}
