//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpNetCoreDesafioB2.Queries.Filters {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FiltersQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FiltersQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpNetCoreDesafioB2.Queries.Filters.FiltersQueries", typeof(FiltersQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TRUNCATE TABLE  mantis_filters_table.
        /// </summary>
        internal static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO mantis_filters_table (user_id, project_id,is_public,NAME,filter_string) VALUES  (&apos;1&apos;,&apos;0&apos;,&apos;0&apos;,&apos;REQ&apos;,&apos;v9#{&quot;_version&quot;:&quot;v9&quot;,&quot;_view_type&quot;:&quot;simple&quot;,&quot;category_id&quot;:[&quot;0&quot;],&quot;severity&quot;:[0],&quot;status&quot;:[0],&quot;highlight_changed&quot;:6,&quot;reporter_id&quot;:[0],&quot;handler_id&quot;:[0],&quot;project_id&quot;:[-3],&quot;resolution&quot;:[0],&quot;build&quot;:[&quot;0&quot;],&quot;version&quot;:[&quot;0&quot;],&quot;hide_status&quot;:[90],&quot;monitor_user_id&quot;:[0],&quot;sort&quot;:&quot;last_updated&quot;,&quot;dir&quot;:&quot;DESC&quot;,&quot;per_page&quot;:50,&quot;match_type&quot;:0,&quot;platform&quot;:[&quot;0&quot;],&quot;os&quot;:[&quot;0&quot;],&quot;os_build&quot;:[&quot;0&quot;],&quot;fixed_in_version&quot;:[&quot;0&quot;],&quot;target_versi [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string InsertOneFilter {
            get {
                return ResourceManager.GetString("InsertOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id,name from mantis_filters_table 
        ///ORDER BY RAND()
        ///LIMIT 1.
        /// </summary>
        internal static string SearchFilterRandom {
            get {
                return ResourceManager.GetString("SearchFilterRandom", resourceCulture);
            }
        }
    }
}
