//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestSharpNetCoreDesafioB2.Queries.Issues {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IssuesQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IssuesQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestSharpNetCoreDesafioB2.Queries.Issues.IssuesQueries", typeof(IssuesQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id,bug_id FROM mantis_bugnote_table
        ///ORDER BY id DESC
        ///LIMIT 1.
        /// </summary>
        internal static string GetNoteIssues {
            get {
                return ResourceManager.GetString("GetNoteIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT ID FROM mantis_bug_table
        ///ORDER BY ID DESC
        ///LIMIT 1.
        /// </summary>
        internal static string GetOneIssues {
            get {
                return ResourceManager.GetString("GetOneIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id, summary FROM mantis_bug_table ORDER BY RAND() LIMIT 1;.
        /// </summary>
        internal static string SearchIdIssuesRandom {
            get {
                return ResourceManager.GetString("SearchIdIssuesRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT a.id, a.summary, b.description, c.id, c.name, a.category_id, d.name, e.id, e.username, e.realname, e.email,  a.status, a.resolution , a.view_state, a.priority, a.severity, a.reproducibility, 
        ///a.sticky, DATE_FORMAT(FROM_UNIXTIME(a.date_submitted), &quot;%d/%m/%Y %T&quot;) AS created_at,  DATE_FORMAT(FROM_UNIXTIME(a.last_updated),  &quot;%d/%m/%Y %T&quot;)  AS updated_at , DATE_FORMAT(FROM_UNIXTIME(f.date_modified),  &quot;%d/%m/%Y %T&quot;)  AS created_at ,f.user_id, g.username, g.realname, g.email, f.type
        ///FROM mantis_bug_table  [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string SearchIssuesRandom {
            get {
                return ResourceManager.GetString("SearchIssuesRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT id,bug_id FROM mantis_bugnote_table
        ///ORDER BY id DESC
        ///LIMIT 1.
        /// </summary>
        internal static string SearchNotes {
            get {
                return ResourceManager.GetString("SearchNotes", resourceCulture);
            }
        }
    }
}
